version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/dev
    ports:
      - '80:80'
      - '2000:2000'
      - '3000:3000'
      - '4000:4000'
      - '5000:5000'
      - '7000:7000'
      - '8000:8000'
      - '9000:9000'
    volumes:
      - /:/etc/ssl
      - /:/etc/letsencrypt
      - /:/data/letsencrypt
