version: '3.4'
services:
  homepage:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage
    restart: on-failure
    environment:
      NODE_ENV: production
      BASE_URL: https://mattlovan.com
      GHOST_PATH: https://content.mattlovan.com
      GHOST_KEY: 56c748b686a94f2f5ea7cd0f64

  content:
    image: 'ghost:latest'
    container_name: content
    restart: on-failure
    environment:
      url: https://content.mattlovan.com
    volumes:
      - ./data/ghost:/var/lib/ghost/content

  midifighter:
    image: 'magrelo/midifighter:latest'
    container_name: homepage
    restart: on-failure

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  dk-chart:
    image: 'magrelo/dk-chart:latest'
    container_name: dk-chart
    restart: on-failure
    environment:
      - MONGODB_URL_INT=mongodb://${APP_MONGO_USER}:${APP_MONGO_PASS}@mongodb:27017/${APP_MONGO_DB}
      - INIT_DB=${INIT_DB}

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    hostname: 'mongodb'
    ports:
      - '27000:27000'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_REPLICA_SET_NAME=${MONGO_REPLICA_SET_NAME}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_DB=${APP_MONGO_DB}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}
    volumes:
      - ./data/db:/data/db
      - ./mongo/createUsers.sh:/docker-entrypoint-initdb.d/createUsers.sh:ro
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_ROOT_USERNAME} -p $${MONGO_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: mongod --oplogSize 128 --replSet ${MONGO_REPLICA_SET_NAME}
