version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  homepage:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage
    restart: on-failure

  midifighter:
    image: 'magrelo/midifighter:latest'
    container_name: midifighter
    restart: on-failure

  garden:
    image: 'magrelo/communitygarden:latest'
    container_name: garden
    restart: on-failure

  souvenir:
    image: 'magrelo/souvenir:latest'
    container_name: souvenir
    restart: on-failure

  signatures:
    image: 'magrelo/signingdemo:latest'
    container_name: signingdemo
    restart: on-failure
    environment:
      - MONGODB_URL_INT=mongodb://mongodb:27017/signingdemo
    depends_on:
      - mongodb

  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
