version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  homepage:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage
    restart: on-failure

  homepage2:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage2
    restart: on-failure

  homepage3:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage3
    restart: on-failure

  # app:
  #   image: 241820317069.dkr.ecr.us-east-1.amazonaws.com/system-interfaces:latest
  #   container_name: pragma-app
  #   environment:
  #     - NODE_ENV=production
  #     - ENV=production
  #     - MONGODB_URL_INT=mongodb://mongodb:27017/pragma_bondAuction
  #   links:
  #     - mongodb
  #     - publicnode
  #   depends_on:
  #     - mongodb
  #     - publicnode
  #   restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./nginx/dev
    ports:
      - '80:80'
      - '2000:2000'
      - '3000:3000'
