version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  homepage:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage
    restart: on-failure

  midifighter:
    image: 'magrelo/midifighter:latest'
    container_name: midifighter
    restart: on-failure

  garden:
    image: 'magrelo/communitygarden:latest'
    container_name: garden
    restart: on-failure

  souvenir:
    image: 'magrelo/souvenir:latest'
    container_name: souvenir
    restart: on-failure

  signatures:
    image: 'magrelo/signingdemo:latest'
    container_name: signingdemo
    restart: on-failure
    environment:
      - MONGODB_URL_INT=mongodb://mongodb:27017/signingdemo
    depends_on:
      - mongodb

  golf:
    image: 'magrelo/golf-page:latest'
    container_name: golf
    restart: on-failure
    environment:
      - MONGODB_URL_INT=mongodb://mongodb:27017/golf

  referral:
    image: 'magrelo/referral:latest'
    container_name: referral
    restart: on-failure
    environment:
      - MONGODB_URL_INT=mongodb://mongodb:27017/referral

  oneshot:
    image: 'magrelo/oneshot:latest'
    container_name: oneshot
    restart: on-failure
    environment:
      - MONGODB_URL_INT=mongodb://mongodb:27017/oneshot
    command: 'npm start'
    depends_on:
      - mongodb

  netstats:
    container_name: netstats
    build: ./eth-netstats
    environment:
      - TZ=`ls -la /etc/localtime | cut -d/ -f8-9
      - WS_SECRET=eth-net-stats-secret
    restart: on-failure
  miner:
    container_name: miner
    hostname: miner
    build: ./monitored-geth-client
    depends_on:
      - netstats
    environment:
      - TZ=`ls -la /etc/localtime | cut -d/ -f8-9
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --networkid=654321
      --mine --targetgaslimit="9000000000000"
      --unlock="007ccffb7916f37f7aeef05e8096ecfbe55afc2f" --password="/root/files/password.txt"
      --rpc --rpcaddr="0.0.0.0" --rpccorsdomain="*" --rpcapi "db,eth,net,web3"
      --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322'
    restart: on-failure
  publicnode:
    container_name: publicnode
    hostname: publicnode
    build: ./monitored-geth-client
    depends_on:
      - miner
      - netstats
    environment:
      - TZ=`ls -la /etc/localtime | cut -d/ -f8-9
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --networkid=654321
      --ws --wsaddr="0.0.0.0" --wsorigins="*"
      --rpc --rpcaddr="0.0.0.0" --rpccorsdomain="*" --rpcapi "db,eth,net,web3"
      --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
      - '8545:8545'
      - '8546:8546'
      - '30303:30303'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
