version: '3'
services:
  nginx:
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
      - '3000:3000'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
